### PR TITLE
Add Language client neovim

### PR DESCRIPTION
**Pull request by hrsh7th**

### CODE REVIEW

**Comment by Shatur95** [comment]
I noticed that it prints `=<SNR>`89 _on_complete_done_after()` in cmd. Is it expected?

**Comment by hrsh7th** [comment]
Fixed.

**Comment by Shatur95** [comment]
Thank you!

**Comment by Shatur95** [comment]
> I noticed that it prints =<SNR>89 _on_complete_done_after() in cmd. Is it expected?

This message still prints after custom snippet completion (non-LSP) even after the fix.

**Comment by hrsh7th** [comment]
Hm... My environment display message but a moment.
Could you tell me more details the problem?

**Comment by Shatur95** [comment]
After expanding the custom snippet, I see this message in cmd until I enter a new command:
[asciicast](https://asciinema.org/a/bbxFbArep0tvOqd7Ii4Cq9vdS)

**Comment by hrsh7th** [comment]
Thanks for your explanation.
I've fixed in master.
Could you test it?

**Comment by Shatur95** [comment]
Yes, it helps, thanks!

**Pull request merged**
