### PR TITLE
Support new vim-lsp integration

### PR DESCRIPTION
**Pull request by hrsh7th**

### CODE REVIEW

**Comment by prabirshrestha** [comment]
@hrsh7th Can this be merged now?

**Comment by hrsh7th** [comment]
Yes! Thanks for your ping.

**Comment by prabirshrestha** [comment]
@hrsh7th I tried to use simple `clang` `for` loop snippets and it doesnt seem to work. Do you have it working?

**Comment by prabirshrestha** [comment]
Seems like issue with this mapping. The one in readme seems to work.

```vim
imap <expr> <Tab>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : (pumvisible() ? "\<c-n>" : "\<tab>")
smap <expr> <Tab>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : (pumvisible() ? "\<c-n>" : "\<tab>")
imap <expr> <S-Tab> vsnip#available(-1) ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
smap <expr> <S-Tab> vsnip#available(-1) ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
```

**Comment by hrsh7th** [comment]
Thanks for your reporting.
My environment seems to works well.
`<Tab>` seems often conflict with another mapping.
I think I should be better to change the README.md's mappings maybe.

**Pull request merged**
